[package]
name = "swc_plugin_transform_import"
version = "0.0.1"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
convert_case = "0.6.0"
serde = "1"
serde_json = "1.0.79"
swc_common = { version = "0.33.12", features = ["concurrent"] }
swc_core = { version = "0.87.3", features = ["ecma_quote", "ecma_plugin_transform"] }
swc_ecma_ast = "0.110.15"
swc_ecma_utils = "0.125.0"
swc_ecma_visit = "0.96.15"
swc_plugin_macro = "0.9.15"
swc_plugin_proxy = "0.39.15"
tracing = { version = "0.1.37", features = ["release_max_level_off"] }

[dev-dependencies]
testing = "0.35.14"
swc_ecma_parser = "0.141.33"
swc_ecma_transforms_react = "0.181.3"
swc_ecma_transforms_testing = "0.138.1"
